timeout: 30m
steps:
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -r
      - gs://artifacts.$PROJECT_ID.appspot.com/artifacts/$BRANCH_NAME/.m2
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - .
      - -t
      - gcr.io/$PROJECT_ID/glymur
  # - name: gcr.io/cloud-builders/docker
  #   args:
  #     - run
  #     - --volume=/workspace/:/root/
  #     - --volume=/workspace/.m2:/root/.m2/repository
  #     - gcr.io/$PROJECT_ID/glymur
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -r
      - .m2
      - gs://artifacts.$PROJECT_ID.appspot.com/artifacts/$BRANCH_NAME
