timeout: 30m
steps:
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -r
      - gs://artifacts.$PROJECT_ID.appspot.com/artifacts/$BRANCH_NAME/.m2
      - .
  - name: 'ubuntu'
    args: ['bash', './build.sh']
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -r
      - .m2
      - gs://artifacts.$PROJECT_ID.appspot.com/artifacts/$BRANCH_NAME
